package com.natiqhaciyef.android_safe_mode_util.constants

const val EMPTY_STRING = ""
const val FOUR_SPACE = "    "
const val SPACE = " "
const val SLASH = "/"
const val DOT = "."
const val COMMA = ","
const val COLON = ":"
const val SEMI_COLON = ";"
const val AMPERSAND = "&"
const val EXCLAMATION = "!"
const val PERCENT = "%"
const val DOLLAR = "$"
const val PLUS = "+"
const val MINUS = "-"
const val STAR = "*"
const val CENTER_DOT = "●"
const val AT_THE_RATE_SIGN = "@"
const val HASH = "#"
const val EQUAL = "="
const val LINE = "-"


const val NULL = "null"
const val FORMATTED_NUMBER_ONE = "%.1f"
const val FORMATTED_NUMBER_TWO = "%.2f"
const val FORMATTED_ALGORITHM = "%02x"
const val FORMATTED_DATE = "dd.MM.yyyy"
const val FORMATTED_DATE_TIME = "dd.MM.yyyy HH:mm"
const val EMAIL_SUFFIX = "@gmail.com"
